Dealing with dates and times in pandas

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Asian_paints.csv')

In [3]:
df.head()

              DateTime  Pre Open ASIANPAINTEQN  ASIANPAINTEQN
0  2025-06-13 09:00:59                  2200.0            NaN
1  2025-06-13 09:01:59                  2199.0            NaN
2  2025-06-13 09:02:59                  2190.0            NaN
3  2025-06-13 09:03:59                  2187.0            NaN
4  2025-06-13 09:04:59                  2187.0            NaN

Now trying to get dayname for one value

In [4]:
df.loc[0, 'DateTime'].day_name()

AttributeError: 'str' object has no attribute 'day_name'

We got error because here the column is str datatype and we have to change it to datetime type

In [5]:
df['DateTime'] = pd.to_datetime(df['DateTime'], format = '%Y-%m-%d %H:%M:%S')

In [6]:
df.loc[0, 'DateTime'].day_name()

'Friday'

Now trying to get the dayname for entire datetime column(series datatype)

In [7]:
df['DateTime'].day_name()

AttributeError: 'Series' object has no attribute 'day_name'

We have to apply the date method to apply it for entire series object

In [9]:
df['DateTime'].dt.day_name()

0      Friday
1      Friday
2      Friday
3      Friday
4      Friday
        ...
393    Friday
394    Friday
395    Friday
396    Friday
397    Friday
Name: DateTime, Length: 398, dtype: object

To view the oldest and latest dates

In [10]:
df['DateTime'].min()

Timestamp('2025-06-13 09:00:59')

In [11]:
df['DateTime'].max()

Timestamp('2025-06-13 15:59:48')

To view the time gap between these 2, use timedeltas

In [12]:
df['DateTime'].max() - df['DateTime'].min()

Timedelta('0 days 06:58:49')

In [16]:
filter = (df['DateTime'].dt.hour >= 14)
df.loc[filter]

               DateTime  Pre Open ASIANPAINTEQN  ASIANPAINTEQN
293 2025-06-13 14:00:58                     NaN         2212.2
294 2025-06-13 14:01:59                     NaN         2211.0
295 2025-06-13 14:02:59                     NaN         2210.7
296 2025-06-13 14:03:57                     NaN         2210.6
297 2025-06-13 14:04:59                     NaN         2210.7
..                  ...                     ...            ...
393 2025-06-13 15:52:45                     NaN         2214.2
394 2025-06-13 15:55:39                     NaN         2214.2
395 2025-06-13 15:56:44                     NaN         2214.2
396 2025-06-13 15:58:41                     NaN         2214.2
397 2025-06-13 15:59:48                     NaN         2214.2

[105 rows x 3 columns]

In [15]:
df['DateTime'].dt.hour

0       9
1       9
2       9
3       9
4       9
       ..
393    15
394    15
395    15
396    15
397    15
Name: DateTime, Length: 398, dtype: int32